[package]
name = "mcg"
authors = ["kraxarn"]
description = "Mobile card games"
edition = "2021"

version = "0.0.1"

# hi :3

[dependencies]
bevy = "0.9"
strum = "0.24"
strum_macros = "0.24"
fastrand = "1.8"