name: Android (Docker)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: docker://notfl3/cargo-apk:latest
      - uses: actions/checkout@v2

      - name: Build
        run: cargo quad-apk build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: mcg-android
          path: ${{runner.workspace}}/mcg/target/android-artifacts/release/apk/mcg.apk
