name: Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: Install Android target
        run: rustup target add aarch64-linux-android

      - name: Install Cargo APK
        run: cargo install cargo-apk

      - name: Prepare APK sign
        working-directory: ${{runner.workspace}}/mcg/android
        env:
          KEYSTORE: ${{secrets.KEYSTORE}}
          ALIAS: ${{secrets.KEYSTORE_ALIAS}}
          PASSWORD: ${{secrets.KEYSTORE_PASSWORD}}
        run: |
          echo -n "$KEYSTORE" | base64 -d > "keystore.jks"
          echo "[package.metadata.android.signing.release]" >> Cargo.toml
          echo "path = \"keystore.jks\"" >> Cargo.toml
          echo -e "keystore_alias = \"$ALIAS\"" >> Cargo.toml
          echo -e "keystore_password = \"$PASSWORD\"" >> Cargo.toml

      - name: Build
        working-directory: ${{runner.workspace}}/mcg/android
        run: ANDROID_NDK_ROOT=$ANDROID_NDK_LATEST_HOME cargo apk build --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mcg-android
          path: ${{runner.workspace}}/mcg/target/release/apk/mcg.apk
