name: Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: notfl3/cargo-apk:latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: cargo quad-apk build --release

      - name: Sign APK
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: ${{runner.workspace}}/mcg/target/android-artifacts/release
          signingKeyBase64: ${{secrets.KEYSTORE}}
          alias: ${{secrets.KEYSTORE_ALIAS}}
          keyStorePassword: ${{secrets.KEYSTORE_PASSWORD}}
          keyPassword: ${{secrets.KEYSTORE_PASSWORD}}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: mcg-android
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
