name: Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container: notfl3/cargo-apk:latest

    steps:
      - uses: actions/checkout@v2

      # Temporary workaround
      - name: Checkout submodules
        working-directory: ${{runner.workspace}}/mcg
        run: |
          git clone https://github.com/kraxarn/miniquad.git miniquad-android

      - name: Build
        run: cargo quad-apk build --release

      - name: Sign APK
        working-directory: ${{runner.workspace}}
        env:
          KEYSTORE: ${{secrets.KEYSTORE}}
          ALIAS: ${{secrets.KEYSTORE_ALIAS}}
          PASSWORD: ${{secrets.KEYSTORE_PASSWORD}}
        run: |
          echo -n "$KEYSTORE" | base64 -d > "keystore.jks"
          apksigner sign --ks "keystore.jks" --ks-key-alias "$ALIAS" --ks-pass "pass:$PASSWORD" "mcg/target/android-artifacts/release/apk/mcg.apk"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: mcg-android
          path: ${{runner.workspace}}/mcg/target/android-artifacts/release/apk/mcg.apk
