name: Export

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download Engine
        run: |
          curl -L https://github.com/godotengine/godot/releases/download/3.4-stable/Godot_v3.4-stable_mono_linux_headless_64.zip -o godot.zip
          unzip godot.zip
          rm -f godot.zip
          ln -s ./Godot_v3.4-stable_mono_linux_headless_64/Godot_v3.4-stable_mono_linux_headless.64 ./godot
          echo "Godot $(./godot --version)"

      - name: Download Export Templates
        run: |
          curl -L https://github.com/godotengine/godot/releases/download/3.4-stable/Godot_v3.4-stable_mono_export_templates.tpz -o templates.zip
          unzip templates.zip
          rm -f templates.zip
          TEMPLATES_VERSION="$(cat ./templates/version.txt)"
          TEMPLATES_DIR="$HOME/.local/share/godot/templates"
          mkdir -p "$TEMPLATES_DIR"
          mv "./templates" "$TEMPLATES_DIR/$TEMPLATES_VERSION"
          echo "Templates $TEMPLATES_VERSION"

      - name: Export Project - Linux/X11
        run: /godot --path "./mcg" --export "Linux/X11"

      - name: Export Project - Windows Desktop
        run: /godot --path "./mcg" --export "Windows Desktop"

      - name: Export Project - Mac OSX
        run: /godot --path "./mcg" --export "Mac OSX"

      - name: Export Project - Android
        run: /godot --path "./mcg" --export "Android"

      - name: Export Project - HTML5
        run: /godot --path "./mcg" --export "HTML5"

      - name: Upload Artifact - Linux/X11
        uses: actions/upload-artifact@v2
        with:
          name: mcg-linux-x11
          path: ${{runner.workspace}}/mcg/Export/LinuxX11

      - name: Upload Artifact - Windows Desktop
        uses: actions/upload-artifact@v2
        with:
          name: mcg-windows-desktop
          path: ${{runner.workspace}}/mcg/Export/WindowsDesktop

      - name: Upload Artifact - Mac OSX
        uses: actions/upload-artifact@v2
        with:
          name: mcg-mac-osx
          path: ${{runner.workspace}}/mcg/Export/MacOsx

      - name: Upload Artifact - Android
        uses: actions/upload-artifact@v2
        with:
          name: mcg-android
          path: ${{runner.workspace}}/mcg/Export/Android

      - name: Upload Artifact - HTML5
        uses: actions/upload-artifact@v2
        with:
          name: mcg-html5
          path: ${{runner.workspace}}/mcg/Export/HTML5