name: Export

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Export Game
        uses: firebelley/godot-export@v3
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/3.4-stable/Godot_v3.4-stable_mono_linux_headless_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/3.4-stable/Godot_v3.4-stable_mono_export_templates.tpz
          relative_project_path: .

      - name: Upload Artifact - Linux/X11
        uses: actions/upload-artifact@v2
        with:
          name: mcg-linux-x11
          path: ${{runner.workspace}}/Export/LinuxX11

      - name: Upload Artifact - Windows Desktop
        uses: actions/upload-artifact@v2
        with:
          name: mcg-windows-desktop
          path: ${{runner.workspace}}/Export/WindowsDesktop

      - name: Upload Artifact - Mac OSX
        uses: actions/upload-artifact@v2
        with:
          name: mcg-mac-osx
          path: ${{runner.workspace}}/Export/MacOsx

      - name: Upload Artifact - Android
        uses: actions/upload-artifact@v2
        with:
          name: mcg-android
          path: ${{runner.workspace}}/Export/Android
          
      - name: Upload Artifact - HTML5
        uses: actions/upload-artifact@v2
        with:
          name: mcg-html5
          path: ${{runner.workspace}}/Export/HTML5