name: HTML5

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GODOT_VERSION: 3.4

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Engine
        id: cache-engine
        uses: actions/cache@v2
        with:
          path: godot.zip
          key: godot-v${{env.GODOT_VERSION}}-${{runner.os}}

      - name: Download Engine
        if: steps.cache-engine.outputs.cache-hit != 'true'
        run: curl -L https://github.com/godotengine/godot/releases/download/$GODOT_VERSION-stable/Godot_v$GODOT_VERSION-stable_mono_linux_headless_64.zip -o godot.zip

      - name: Install Engine
        run: |
          unzip godot.zip
          ln -s ./Godot_v$GODOT_VERSION-stable_mono_linux_headless_64/Godot_v$GODOT_VERSION-stable_mono_linux_headless.64 ./godot

      - name: Cache Export Templates
        id: cache-templates
        uses: actions/cache@v2
        with:
          path: templates.zip
          key: templates-v${{env.GODOT_VERSION}}-${{runner.os}}

      - name: Download Export Templates
        if: steps.cache-templates.outputs.cache-hit != 'true'
        run: curl -L https://github.com/godotengine/godot/releases/download/$GODOT_VERSION-stable/Godot_v$GODOT_VERSION-stable_mono_export_templates.tpz -o templates.zip

      - name: Install Export Templates
        run: |
          unzip templates.zip
          TEMPLATES_VERSION="$(cat ./templates/version.txt)"
          TEMPLATES_DIR="$HOME/.local/share/godot/templates"
          mkdir -p "$TEMPLATES_DIR"
          mv "./templates" "$TEMPLATES_DIR/$TEMPLATES_VERSION"

      - name: Export Project
        run: |
          mkdir -p ${{runner.workspace}}/mcg/Export/HTML5
          ./godot --verbose --path "${{runner.workspace}}/mcg" --export "HTML5"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: mcg-html5
          path: ${{runner.workspace}}/mcg/Export/HTML5
