name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: Install Dependencies
        run: sudo apt install g++ pkg-config libx11-dev libasound2-dev libudev-dev

      - name: Build
        run: cargo build --package mcg-desktop --release

      - name: Test
        run: cargo test --package mcg-desktop --release

      - name: Bundle
        run: |
          mkdir ${{runner.workspace}}/build
          cp ${{runner.workspace}}/mcg/target/release/mcg-desktop ${{runner.workspace}}/build/
          cp -r ${{runner.workspace}}/mcg/assets ${{runner.workspace}}/build/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mcg-linux
          path: ${{runner.workspace}}/build
