name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install libx11-dev libxi-dev libgl1-mesa-dev libasound2-dev

      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: mcg-linux
          path: |
            ${{runner.workspace}}/mcg/target/release/mcg
            ${{runner.workspace}}/mcg/assets
