name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test --release

      - name: Bundle
        run: |
          mkdir ${{runner.workspace}}/build
          cp ${{runner.workspace}}/mcg/target/release/mcg ${{runner.workspace}}/build/
          cp -r ${{runner.workspace}}/mcg/assets ${{runner.workspace}}/build/

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: mcg-macos
          path: ${{runner.workspace}}/build
