name: Node.js

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm install
      - env:
          NAKAMA_HOST: ${{secrets.NAKAMA_HOST}}
          NAKAMA_SERVER_KEY:
            ${{secrets.NAKAMA_SERVER_KEY}}
        run: npm run build --if-present

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: mcg
          path: build
