name: Node.js

on:
  push:
    branches: [ web ]
  pull_request:
    branches: [ web ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm run build --if-present
