name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Project
        working-directory: ${{runner.workspace}}
        run: msbuild Tests -t:rebuild -property:configuration=release
