name: Wasm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - name: Install WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Install WASM tools
        run: cargo install wasm-bindgen-cli

      - name: Build
        run: cargo build --package mcg-wasm --target wasm32-unknown-unknown --release

      - name: Bundle
        run: |
          mkdir ${{runner.workspace}}/build
          wasm-bindgen --out-dir ${{runner.workspace}}/build --target web ${{runner.workspace}}/mcg/target/wasm32-unknown-unknown/release/mcg-wasm.wasm
          cp -r ${{runner.workspace}}/mcg/mcg-wasm/res ${{runner.workspace}}/build/
          cp -r ${{runner.workspace}}/mcg/assets ${{runner.workspace}}/build/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ${{runner.workspace}}/build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mcg-wasm
          path: ${{runner.workspace}}/build
